variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/test.yml'

.cuda:
  extends: .test
  before_script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
  script:
    - julia --project -e 'using Pkg;
                          Pkg.update();
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'

test:v1.0:
  extends: .cuda
  variables:
    CI_VERSION_TAG: 'v1.0'

test:v1.1:
  extends: .cuda
  variables:
    CI_VERSION_TAG: 'v1.1'

test:v1.2:
  extends: .cuda
  variables:
    CI_VERSION_TAG: 'v1.2'

test:v1.3:
  extends: .cuda
  variables:
    CI_VERSION_TAG: 'v1.3'

test:dev:
  extends: .cuda
  allow_failure: true
  variables:
    CI_VERSION_TAG: 'v1.0'

coverage:
  stage: post
  extends: .root
  variables:
    CI_VERSION_TAG: 'v1.2'
  script:
    - julia --project -e 'using Pkg;
                          Pkg.add("Coverage")'
    - julia --project -e 'using Coverage;
                          cl, tl = get_summary(process_folder());
                          println("(", cl/tl*100, "%) covered");
                          Codecov.submit_local(Codecov.process_folder(), ".");
                          Coveralls.submit_local(Coveralls.process_folder(), ".")'
  coverage: '/\(\d+.\d+\%\) covered/'
